"""Write replay_detector_corpus.jsonl + review.html from proposed labels.

Produces two outputs:

  files/logs/replay_detector_corpus.jsonl
      - One JSON line per clip, schema as agreed with the user
      - Regions are listed as [start_s, end_s] pairs, 0.5s rounded

  files/logs/replay_detector_corpus/review.html
      - Minimal viewer: per-clip video + SVG timeline overlay showing
        proposed live/replay regions + contact sheet reference

The labels here are the agent's first pass from contact-sheet visual
inspection (see PROPOSED_LABELS below).  Per-clip uncertainty is
noted explicitly.  Human reviewer corrects via direct edit of the
JSONL; the review HTML is regenerated by re-running this script.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CORPUS_DIR = ROOT / "logs" / "replay_detector_corpus"
JSONL = ROOT / "logs" / "replay_detector_corpus.jsonl"
REVIEW_HTML = CORPUS_DIR / "review.html"

# Schema agreed with user:
#   session               : str (match session id)
#   delivery_id           : str (dNNN)
#   clip_key              : str (stable id for this corpus)
#   mp4_rel               : str (relative to review.html)
#   sheet_rel             : str (relative to review.html)
#   duration_s            : float
#   event_type            : str
#   runs                  : int | null
#   label                 : CLEAN | CLEAN_POST_BOUNDARY | MIXED_FRONT
#                          | MIXED_BACK | REPLAY_POLLUTED
#   live_regions          : [[start_s, end_s], ...]
#   replay_regions        : [[start_s, end_s], ...]
#   prior_event_was_boundary_or_wicket : bool
#   inter_event_s         : float | null
#   notes                 : str
#   confidence            : "high" | "medium" | "low"
#   labeller              : "ai_first_pass_contact_sheets"
#   ambiguity_notes       : str (boundaries where we're unsure)

# Load clip metadata (built by replay_corpus_builder.py)
CLIPS_INDEX = json.loads(
    (CORPUS_DIR / "clips_index.json").read_text())
CLIPS_BY_KEY = {c["clip_key"]: c for c in CLIPS_INDEX}


def dur(clip_key: str) -> float:
    return CLIPS_BY_KEY[clip_key]["duration_s"]


# Boundaries below are proposed from visual inspection of 25-thumb
# contact sheets (~0.7-1.0s sampling interval). Treat ±0.7s at any
# boundary as the expected label noise floor; anywhere explicit
# ambiguity is noted the human reviewer should correct.
PROPOSED_LABELS: list[dict] = [
    {
        "clip_key": "c01_d002_extra",
        "event_type": "EXTRA",
        "runs": 1,
        "label": "CLEAN",
        "live_regions": [[0.0, dur("c01_d002_extra")]],
        "replay_regions": [],
        "prior_event_was_boundary_or_wicket": False,
        "confidence": "high",
        "ambiguity_notes": "",
    },
    {
        "clip_key": "c02_d008_single",
        "event_type": "1_RUNS",
        "runs": 1,
        "label": "CLEAN",
        "live_regions": [[0.0, dur("c02_d008_single")]],
        "replay_regions": [],
        "prior_event_was_boundary_or_wicket": False,
        "confidence": "high",
        "ambiguity_notes": "0-2.5s is pitch-analytics graphic overlay "
                          "(NOOB AVERAGE LENGTH); tail 17.5-22.3s looks "
                          "like strategic-timeout promo. Neither is a "
                          "slow-mo replay of a prior ball, so treating "
                          "as CLEAN.",
    },
    {
        "clip_key": "c03_d019_defensive",
        "event_type": "DOT",
        "runs": 0,
        "label": "CLEAN",
        "live_regions": [[0.0, dur("c03_d019_defensive")]],
        "replay_regions": [],
        "prior_event_was_boundary_or_wicket": False,
        "confidence": "high",
        "ambiguity_notes": "Low-motion defensive fielder positioning "
                          "at start (0-4.8s). Key RC-2 test: the "
                          "low-motion section must NOT be flagged as "
                          "slow-motion — it's legitimate live content.",
    },
    {
        "clip_key": "c04_d023_anchor",
        "event_type": "2_RUNS",
        "runs": 2,
        "label": "CLEAN",
        "live_regions": [[0.0, dur("c04_d023_anchor")]],
        "replay_regions": [],
        "prior_event_was_boundary_or_wicket": False,
        "confidence": "high",
        "ambiguity_notes": "User-anchored CLEAN. Clip contains live "
                          "delivery + normal sponsor/close-up content. "
                          "No slow-mo replays of prior balls.",
    },
    {
        "clip_key": "c05_d024_anchor",
        "event_type": "2_RUNS",
        "runs": 2,
        "label": "CLEAN",
        "live_regions": [[0.0, dur("c05_d024_anchor")]],
        "replay_regions": [],
        "prior_event_was_boundary_or_wicket": False,
        "confidence": "high",
        "ambiguity_notes": "User-anchored CLEAN. Heavy crowd / sponsor "
                          "content in first ~4s and last ~4s; delivery "
                          "+ diving fielder visible around 9-13s.",
    },
    {
        "clip_key": "c06_d039_post_four",
        "event_type": "1_RUNS",
        "runs": 1,
        "label": "CLEAN_POST_BOUNDARY",
        "live_regions": [[0.0, dur("c06_d039_post_four")]],
        "replay_regions": [],
        "prior_event_was_boundary_or_wicket": True,
        "confidence": "high",
        "ambiguity_notes": "USER-CONFIRMED CLEAN_POST_BOUNDARY. No "
                          "residual replay of d038 FOUR. First ~3.5s is "
                          "pre-delivery live content (fielder at "
                          "boundary rope / crowd context). Live d039 "
                          "delivery in the middle. Tail ~11-15.4s is a "
                          "car sponsor ad (non-cricket broadcast "
                          "content, but not slow-mo replay). "
                          "Gold-standard tight-timing CLEAN_POST_BOUNDARY "
                          "test (22.5s after d038 FOUR).",
    },
    {
        "clip_key": "c07_d069_post_six",
        "event_type": "1_RUNS",
        "runs": 1,
        "label": "CLEAN_POST_BOUNDARY",
        "live_regions": [[0.0, dur("c07_d069_post_six")]],
        "replay_regions": [],
        "prior_event_was_boundary_or_wicket": True,
        "confidence": "high",
        "ambiguity_notes": "Key CLEAN_POST_BOUNDARY test. No slow-mo of "
                          "prior d068 SIX visible. Live d069 delivery "
                          "at ~1.5-2.5s. The rest is post-delivery live "
                          "content + graphics. RC-1/RC-2 must NOT "
                          "false-positive on this clip.",
    },
    {
        "clip_key": "c08_d027_mixed_front",
        "event_type": "SIX",
        "runs": 6,
        "label": "MIXED_FRONT",
        "live_regions": [[0.0, 4.0]],
        "replay_regions": [[4.0, dur("c08_d027_mixed_front")]],
        "prior_event_was_boundary_or_wicket": False,
        "confidence": "medium",
        "ambiguity_notes": "Live pitch action at start (#00-#03, ~0-2.5s), "
                          "TATA IPL graphic at #00. User estimated "
                          "'first 30-40%' is live; my visible live "
                          "window is shorter (~20% at 0-4s). Rest is "
                          "celebration + tournament-sixes counter "
                          "animation (525→526). Note: no clear "
                          "slow-mo replay visible at 0.7s sampling; "
                          "real replays may sit between thumbnails.",
    },
    {
        "clip_key": "c09_d025_mixed_back",
        "event_type": "SIX",
        "runs": 6,
        "label": "MIXED_BACK",
        "live_regions": [[13.0, dur("c09_d025_mixed_back")]],
        "replay_regions": [[0.0, 13.0]],
        "prior_event_was_boundary_or_wicket": False,
        "confidence": "medium_high",
        "ambiguity_notes": "User-anchored 'last 30-40% is the delivery'. "
                          "First 13s: SIX score flash at start, "
                          "stadium/sponsor close-ups, TATA IPL bridge "
                          "at #13 (~12s). Last ~9s: live delivery — "
                          "USER-CONFIRMED 'no boundary, fielder gets "
                          "the ball comfortably in the outfield', so "
                          "d025's SIX event_type is likely a scorecard "
                          "misread of the real outcome. The front "
                          "replay content is therefore of a DIFFERENT "
                          "prior SIX (not this ball). Boundary "
                          "uncertainty ±1.5s at 13.0s.",
    },
    {
        "clip_key": "c10_d026_mixed_back",
        "event_type": "1_RUNS",
        "runs": 1,
        "label": "MIXED_BACK",
        "live_regions": [[9.0, dur("c10_d026_mixed_back")]],
        "replay_regions": [[0.0, 9.0]],
        "prior_event_was_boundary_or_wicket": True,
        "confidence": "medium_high",
        "ambiguity_notes": "inter_event_s=4.5s after d025 strongly "
                          "suggests this is a phantom event (RC-5 "
                          "should skip it going forward). Front 9s is "
                          "same SIX replay content as d025 (batsman "
                          "close-ups, stadium shots, TATA IPL bridge). "
                          "Back ~7.6s is live pitch action. If reviewer "
                          "judges the back portion is also replay of "
                          "the same ball, move to REPLAY_POLLUTED.",
    },
    {
        "clip_key": "c11_d028_wicket_post_six",
        "event_type": "WICKET",
        "runs": 0,
        "label": "REPLAY_POLLUTED",
        "live_regions": [],
        "replay_regions": [[0.0, dur("c11_d028_wicket_post_six")]],
        "prior_event_was_boundary_or_wicket": True,
        "confidence": "high",
        "ambiguity_notes": "USER-CONFIRMED REPLAY_POLLUTED: 'there is "
                          "no delivery in this'. My earlier "
                          "re-labelling to MIXED_FRONT (reading the "
                          "#00-#04 fielder-diving shot as the wicket "
                          "catch) was wrong — that shot is not d028's "
                          "live wicket delivery. Entire 15.7s clip is "
                          "post-d027-SIX aftermath: fielder-diving "
                          "replay/reaction, slow-mo bowler close-ups, "
                          "TATA IPL bridge, new batter walking in. "
                          "Pairs with c12 as a same-session gold "
                          "REPLAY_POLLUTED case (different broadcast "
                          "session, different event types).",
    },
    {
        "clip_key": "c12_d021_post_six_bakeoff",
        "event_type": "FOUR",
        "runs": 4,
        "label": "REPLAY_POLLUTED",
        "live_regions": [],
        "replay_regions": [[0.0, dur("c12_d021_post_six_bakeoff")]],
        "prior_event_was_boundary_or_wicket": True,
        "confidence": "high",
        "ambiguity_notes": "Cross-session anchor (20260420_202239). "
                          "Diagnosed today: DWR window captured 21.3s "
                          "of post-d020-SIX content with zero live "
                          "d021 FOUR delivery visible. Thumbnails show: "
                          "909 tournament-fours counter, 'FOUR' "
                          "animated graphic, batsman slog close-ups "
                          "(slow-mo replay of d020 SIX), crowd shots, "
                          "strategic-timeout player shots, TATA IPL "
                          "bridge. Gemini in bakeoff described this "
                          "as 'slog into mid, in the air' which "
                          "matches the d020 SIX content, not d021's "
                          "actual FOUR. Gold-standard REPLAY_POLLUTED "
                          "case.",
    },
]


def _round_half(x: float) -> float:
    """Round to nearest 0.5s as per user's resolution requirement."""
    return round(x * 2.0) / 2.0


def _normalize_regions(regions: list[list[float]],
                       clip_duration: float
                       ) -> list[list[float]]:
    """Clamp, sort, round to 0.5s, drop empty intervals."""
    out: list[list[float]] = []
    for a, b in regions:
        a = max(0.0, _round_half(a))
        b = min(clip_duration, _round_half(b))
        if b - a >= 0.5:
            out.append([a, b])
    out.sort()
    return out


def build_jsonl() -> list[dict]:
    records: list[dict] = []
    for p in PROPOSED_LABELS:
        clip = CLIPS_BY_KEY[p["clip_key"]]
        d = clip["duration_s"]
        record = {
            "clip_key": p["clip_key"],
            "session": clip["session"],
            "delivery_id": clip["delivery_id"],
            "mp4_rel": clip["mp4_rel"],
            "sheet_rel": clip["sheet_rel"],
            "duration_s": d,
            "event_type": p["event_type"],
            "runs": p["runs"],
            "label": p["label"],
            "live_regions": _normalize_regions(p["live_regions"], d),
            "replay_regions": _normalize_regions(p["replay_regions"], d),
            "prior_event": clip.get("prior_event"),
            "prior_event_was_boundary_or_wicket":
                p["prior_event_was_boundary_or_wicket"],
            "inter_event_s": clip.get("inter_event_s"),
            "notes": clip.get("notes", ""),
            "confidence": p["confidence"],
            "ambiguity_notes": p["ambiguity_notes"],
            "labeller": "ai_first_pass_contact_sheets",
            "label_resolution_s": 0.5,
        }
        records.append(record)
    return records


def write_jsonl(records: list[dict]) -> None:
    with JSONL.open("w") as f:
        for r in records:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


# ── Review HTML ──────────────────────────────────────────────────────

HTML_HEAD = """<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Replay Detector Corpus — Review</title>
<style>
  :root {
    --bg:#0f1115; --fg:#e6e6e6; --panel:#1a1d23; --muted:#8a94a6;
    --live:#37c978; --replay:#e74c3c; --mixed:#e29c3b;
    --clean:#37c978; --post:#3da5ff; --polluted:#e74c3c;
    --border:#2a2f38;
  }
  html,body{background:var(--bg);color:var(--fg);font:14px/1.45 -apple-system,BlinkMacSystemFont,"SF Pro Text",sans-serif;margin:0}
  header{padding:18px 24px;border-bottom:1px solid var(--border)}
  h1{font-size:18px;margin:0 0 4px 0}
  .sub{color:var(--muted);font-size:12px}
  .wrap{padding:16px 24px 40px 24px;display:flex;flex-direction:column;gap:16px}
  .card{background:var(--panel);border:1px solid var(--border);border-radius:10px;padding:14px 16px;display:grid;grid-template-columns:360px 1fr;gap:16px}
  .card h2{font-size:15px;margin:0 0 4px 0}
  .pill{display:inline-block;padding:1px 9px;border-radius:20px;font-size:11px;margin-right:6px;color:#111;font-weight:600}
  .pill.CLEAN{background:var(--clean)}
  .pill.CLEAN_POST_BOUNDARY{background:var(--post)}
  .pill.MIXED_FRONT,.pill.MIXED_BACK{background:var(--mixed)}
  .pill.REPLAY_POLLUTED{background:var(--polluted);color:#fff}
  .pill.conf-high{background:#37c978}
  .pill.conf-medium_high{background:#77c37a}
  .pill.conf-medium{background:#e29c3b}
  .pill.conf-low{background:#e74c3c;color:#fff}
  video{width:100%;background:#000;border-radius:6px;outline:none}
  .meta{color:var(--muted);font-size:12px;margin-top:6px}
  .notes{margin-top:10px;font-size:12.5px;color:#c9cfda;background:#11141a;padding:8px 10px;border-radius:6px;border-left:3px solid var(--border);white-space:pre-wrap}
  .notes b{color:#e6e6e6}
  .timeline-wrap{margin-top:10px}
  svg.tl{width:100%;height:56px;background:#0b0d12;border-radius:6px;overflow:visible}
  .tl .axis{stroke:#2a2f38;stroke-width:1}
  .tl .tick{fill:var(--muted);font-size:10px}
  .tl .live{fill:var(--live);opacity:0.85}
  .tl .replay{fill:var(--replay);opacity:0.85}
  .tl .label{fill:#fff;font-size:10px;font-weight:600}
  .legend{display:flex;gap:14px;font-size:11px;color:var(--muted);margin-top:6px}
  .legend .sw{display:inline-block;width:12px;height:10px;border-radius:2px;margin-right:4px;vertical-align:-1px}
  details.raw{margin-top:8px;font-size:11px;color:var(--muted)}
  details.raw pre{white-space:pre-wrap;background:#0b0d12;padding:8px 10px;border-radius:6px;border:1px solid var(--border);max-height:220px;overflow:auto}
  .sheet{display:block;width:100%;border-radius:6px;margin-top:10px;border:1px solid var(--border)}
  .sheet-toggle{font-size:11px;color:var(--muted);margin-top:6px;cursor:pointer}
  .head-row{display:flex;gap:16px;flex-wrap:wrap;align-items:baseline}
  .stats{font-size:12px;color:var(--muted)}
</style>
</head>
<body>
<header>
  <h1>Replay Detector Corpus — First-Pass Review</h1>
  <div class="sub">AI-labelled from 25-thumbnail contact sheets. Ground-truth boundaries have ~0.7s noise floor; see per-clip ambiguity notes. Spot-check and edit <code>files/logs/replay_detector_corpus.jsonl</code>, then rerun <code>replay_corpus_review_build.py</code> to regenerate this page.</div>
</header>
<div class="wrap">
"""

HTML_FOOT = "</div></body></html>"


def _tl_svg(record: dict) -> str:
    d = record["duration_s"]
    # 960 is a nominal width; SVG auto-scales to container
    W, H, PAD_L, PAD_R = 960, 56, 40, 10
    inner_w = W - PAD_L - PAD_R

    def x(t: float) -> float:
        return PAD_L + (t / d) * inner_w

    rects = []
    for a, b in record["live_regions"]:
        rects.append(
            f'<rect class="live" x="{x(a):.1f}" y="16" '
            f'width="{(x(b) - x(a)):.1f}" height="16" rx="2"/>')
    for a, b in record["replay_regions"]:
        rects.append(
            f'<rect class="replay" x="{x(a):.1f}" y="16" '
            f'width="{(x(b) - x(a)):.1f}" height="16" rx="2"/>')
    # Axis + ticks every 5s
    ticks = []
    t = 0.0
    while t <= d + 0.001:
        ticks.append(
            f'<line class="axis" x1="{x(t):.1f}" y1="32" '
            f'x2="{x(t):.1f}" y2="38"/>'
            f'<text class="tick" x="{x(t):.1f}" y="50" '
            f'text-anchor="middle">{t:.0f}s</text>')
        t += 5.0
    axis = (f'<line class="axis" x1="{x(0):.1f}" y1="32" '
            f'x2="{x(d):.1f}" y2="32"/>')
    return (f'<svg class="tl" viewBox="0 0 {W} {H}" '
            f'preserveAspectRatio="none">'
            + "".join(rects) + axis + "".join(ticks)
            + "</svg>")


def _card_html(record: dict) -> str:
    label = record["label"]
    conf = record["confidence"]
    live_txt = ", ".join(f"[{a:.1f}, {b:.1f}]"
                         for a, b in record["live_regions"]) or "—"
    repl_txt = ", ".join(f"[{a:.1f}, {b:.1f}]"
                         for a, b in record["replay_regions"]) or "—"
    raw = json.dumps(record, indent=2)
    notes = record["ambiguity_notes"].strip() or "(no specific boundary ambiguity noted)"
    inter = record.get("inter_event_s")
    inter_txt = f"{inter:.1f}s" if inter is not None else "n/a"
    return f"""
<div class="card" id="{record['clip_key']}">
  <div>
    <div class="head-row">
      <h2>{record['clip_key']}</h2>
      <span class="pill {label}">{label}</span>
      <span class="pill conf-{conf}">conf: {conf}</span>
    </div>
    <div class="meta">{record['session']} / {record['delivery_id']} · event={record['event_type']} · runs={record['runs']} · dur={record['duration_s']}s · prior={record.get('prior_event') or '—'} · inter={inter_txt}</div>
    <video controls preload="metadata" src="{record['mp4_rel']}"></video>
    <div class="timeline-wrap">
      {_tl_svg(record)}
      <div class="legend">
        <span><span class="sw" style="background:var(--live)"></span>live</span>
        <span><span class="sw" style="background:var(--replay)"></span>replay</span>
        <span>resolution ±0.5s</span>
      </div>
    </div>
  </div>
  <div>
    <div><b>live_regions:</b> {live_txt}</div>
    <div><b>replay_regions:</b> {repl_txt}</div>
    <div class="notes"><b>Ambiguity / boundary judgement:</b>
{notes}</div>
    <details><summary class="sheet-toggle">▶ contact sheet</summary>
      <img class="sheet" loading="lazy" src="{record['sheet_rel']}" alt="contact sheet" />
    </details>
    <details class="raw"><summary>▶ raw jsonl record</summary><pre>{raw}</pre></details>
  </div>
</div>
"""


def write_review(records: list[dict]) -> None:
    cards = "\n".join(_card_html(r) for r in records)
    REVIEW_HTML.write_text(HTML_HEAD + cards + HTML_FOOT)


if __name__ == "__main__":
    records = build_jsonl()
    write_jsonl(records)
    write_review(records)
    print(f"Wrote {len(records)} records -> {JSONL}")
    print(f"Wrote review HTML          -> {REVIEW_HTML}")
    # Summary
    from collections import Counter
    lbl = Counter(r["label"] for r in records)
    conf = Counter(r["confidence"] for r in records)
    total_live = sum(b - a for r in records for a, b in r["live_regions"])
    total_rep = sum(b - a for r in records for a, b in r["replay_regions"])
    total_dur = sum(r["duration_s"] for r in records)
    print(f"\nLabel distribution: {dict(lbl)}")
    print(f"Confidence: {dict(conf)}")
    print(f"Region totals: live={total_live:.1f}s  replay={total_rep:.1f}s  "
          f"unlabelled={total_dur - total_live - total_rep:.1f}s  "
          f"(total={total_dur:.1f}s)")
